//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp13
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KyrcovaEntities3 : DbContext
    {
        public KyrcovaEntities3()
            : base("name=KyrcovaEntities3")
        {
        }
        private static KyrcovaEntities3 _context;
        public static KyrcovaEntities3 GetContext()
        {
            if (_context == null)
                _context = new KyrcovaEntities3();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classrooms> Classrooms { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Enrollments> Enrollments { get; set; }
        public virtual DbSet<Grades> Grades { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<SessionParticipation> SessionParticipation { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
    }
}
