//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp13
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionParticipation
    {
        public int ParticipationID { get; set; }
        public int StudentID { get; set; }
        public int SessionID { get; set; }
    
        public virtual Sessions Sessions { get; set; }
        public virtual Students Students { get; set; }
    }
}
